import { Vault, normalizePath } from 'obsidian';
import {
	AnnotationEntry,
	AnnotationFile,
	CollectionSummary,
	INDEX_SCHEMA,
	ItemSummary,
	MirrorIndex,
	MirrorState,
	MIRROR_SCHEMA,
	ZoteroCollection,
	ZoteroItem,
	ZoteroItemData,
} from './types';
import { ZoteroMirrorSettings } from './settings';
import { colorName, isoNow, summarizeItem } from './util';

export interface MirrorPaths {
	root: string;
	itemsDir: string;
	annotationsDir: string;
}

const README_TEXT = `# Zotero Mirror

This folder is a **machine-managed mirror** of your Zotero library, written by the
*Zotero Mirror* Obsidian plugin. Do not hand-edit these files — they are
overwritten and reconciled on every sync.

## Layout

- \`items/<key>.json\` — one file per Zotero item (bibliographic records, notes,
  attachments **and** PDF annotations), keyed by Zotero's item key. Content is
  the raw Zotero Web/Local API record.
- \`annotations/<attachmentKey>.json\` — per-PDF aggregated annotation files
  (derived from \`items/\`, regenerated whenever the PDF or its highlights change).
- \`collections.json\` — collections (name + parent tree).
- \`index.json\` — regenerable search index / item summaries (safe to delete;
  rebuilt from \`items/\`).
- \`notes.json\` — registry of generated note views (safe to delete; rebuilt).
- \`.state.json\` — sync cursor (library version, timestamps). Written only when
  something changed, so it stays git-friendly.
- \`README.md\` — this file (only created when missing).

## Using the mirror

Everything is incremental and versioned: commit this folder and you get a
git-history of your whole Zotero library, readable offline, with Zotero closed.

Consumers (Dataview, Templater, other plugins, scripts) can read
\`index.json\` or \`items/<key>.json\` directly.

*Generated by Zotero Mirror.*
`;

/**
 * The on-disk mirror + the in-memory model built from it.
 *
 * Mirror files are written through `vault.adapter` directly (not the vault API)
 * because they are plain JSON data that Obsidian should not index as notes —
 * and it is much faster for thousands of small files. Only generated *notes*
 * (markdown, user-visible) go through the vault API.
 */
export class Mirror {
	private state: MirrorState | null = null;
	private items = new Map<string, ItemSummary>();
	private children = new Map<string, Set<string>>();
	private collections = new Map<string, CollectionSummary>();
	private noteRegistry = new Map<string, string>(); // zotero key -> note path
	private dirtyAttachments = new Set<string>();
	private indexDirty = false;
	private stateDirty = false;
	private collectionsDirty = false;
	private loaded = false;

	constructor(private vault: Vault, private getSettings: () => ZoteroMirrorSettings) {}

	get paths(): MirrorPaths {
		const root = normalizePath(this.getSettings().mirrorFolder || '_zotero');
		return {
			root,
			itemsDir: `${root}/items`,
			annotationsDir: `${root}/annotations`,
		};
	}

	// ---------- path helpers ----------

	private indexPath(): string {
		return `${this.paths.root}/index.json`;
	}
	private statePath(): string {
		return `${this.paths.root}/.state.json`;
	}
	private collectionsPath(): string {
		return `${this.paths.root}/collections.json`;
	}
	private notesPath(): string {
		return `${this.paths.root}/notes.json`;
	}
	private readmePath(): string {
		return `${this.paths.root}/README.md`;
	}
	private itemPath(key: string): string {
		return `${this.paths.itemsDir}/${key}.json`;
	}
	private annotationPath(attachmentKey: string): string {
		return `${this.paths.annotationsDir}/${attachmentKey}.json`;
	}

	private get adapter() {
		return this.vault.adapter;
	}

	/** Fetches the configured mirror folder + name for display. */
	displayRoot(): string {
		return this.paths.root;
	}

	// ---------- (re)initialization ----------

	async ensureDirectories(): Promise<void> {
		const a = this.adapter;
		const p = this.paths;
		for (const dir of [p.root, p.itemsDir, p.annotationsDir]) {
			if (!(await a.exists(dir))) {
				try {
					await a.mkdir(dir);
				} catch (e) {
					// created concurrently / already there
					if (!(await a.exists(dir))) throw e;
				}
			}
		}
		if (!(await a.exists(this.readmePath()))) {
			await this.writeText(this.readmePath(), README_TEXT);
		}
	}

	/** Load state + index (or rebuild the model from item files when needed). */
	async load(): Promise<void> {
		if (this.loaded) return;
		const a = this.adapter;
		this.items.clear();
		this.children.clear();
		this.collections.clear();
		this.state = null;

		if (await a.exists(this.statePath())) {
			try {
				this.state = JSON.parse(await a.read(this.statePath())) as MirrorState;
			} catch {
				this.state = null;
			}
		}
		if (await a.exists(this.indexPath())) {
			try {
				const idx = JSON.parse(await a.read(this.indexPath())) as MirrorIndex;
				if (Array.isArray(idx.items)) {
					for (const it of idx.items) this.upsertSummary(it);
				}
			} catch {
				// corrupt index -> rebuild from item files below
			}
		}
		if (this.items.size === 0 && (await a.exists(this.paths.itemsDir))) {
			await this.scanItemFiles();
		}
		if (await a.exists(this.collectionsPath())) {
			try {
				const c = JSON.parse(await a.read(this.collectionsPath())) as CollectionSummary[];
				if (Array.isArray(c)) for (const col of c) this.collections.set(col.key, col);
			} catch {
				/* ignore */
			}
		}
		if (await a.exists(this.notesPath())) {
			try {
				const n = JSON.parse(await a.read(this.notesPath())) as Record<string, string>;
				for (const [k, v] of Object.entries(n)) if (v) this.noteRegistry.set(k, v);
			} catch {
				/* ignore */
			}
		}
		this.loaded = true;
	}

	private upsertSummary(s: ItemSummary): void {
		this.items.set(s.key, s);
		if (s.parentItem) {
			let set = this.children.get(s.parentItem);
			if (!set) {
				set = new Set();
				this.children.set(s.parentItem, set);
			}
			set.add(s.key);
		}
	}

	private async scanItemFiles(): Promise<void> {
		const a = this.adapter;
		let files: string[] = [];
		try {
			const listed = await a.list(this.paths.itemsDir);
			files = listed.files;
		} catch {
			return;
		}
		for (const f of files) {
			if (!f.endsWith('.json')) continue;
			try {
				const item = JSON.parse(await a.read(f)) as ZoteroItem;
				if (item?.key) this.upsertSummary(summarizeItem(item));
			} catch {
				/* skip unreadable */
			}
		}
	}

	/** Wipe the mirror (except a user-edited README) and forget memory state. */
	async reset(): Promise<void> {
		const a = this.adapter;
		const p = this.paths;
		for (const dir of [p.itemsDir, p.annotationsDir]) {
			if (await a.exists(dir)) {
				try {
					await a.remove(dir);
				} catch {
					/* best effort */
				}
			}
		}
		for (const f of [this.indexPath(), this.statePath(), this.collectionsPath(), this.notesPath()]) {
			if (await a.exists(f)) {
				try {
					await a.remove(f);
				} catch {
					/* best effort */
				}
			}
		}
		this.items.clear();
		this.children.clear();
		this.collections.clear();
		this.noteRegistry.clear();
		this.loaded = true;
		this.setState({
			sourceType: 'local',
			sourceFingerprint: '',
			serverID: null,
			libraryVersion: 0,
			collectionsVersion: 0,
			hasData: false,
			lastSyncedAt: null,
			lastReconcileAt: null,
			lastError: null,
		});
		this.indexDirty = true;
		this.collectionsDirty = true;
		await this.commitDerived(0, false);
	}

	// ---------- accessors ----------

	getState(): MirrorState | null {
		return this.state;
	}

	summary(key: string): ItemSummary | undefined {
		return this.items.get(key);
	}

	summaries(): ItemSummary[] {
		return [...this.items.values()];
	}

	/** Quick mirror statistics from the in-memory index. */
	stats(): { items: number; attachments: number; annotations: number; notes: number; topLevel: number } {
		return this.computeCounts([...this.items.values()]);
	}

	hasItem(key: string): boolean {
		return this.items.has(key);
	}

	childrenOf(parentKey: string): string[] {
		const set = this.children.get(parentKey);
		return set ? [...set] : [];
	}

	collectionName(key: string): string | null {
		return this.collections.get(key)?.name ?? null;
	}

	collectionsList(): CollectionSummary[] {
		return [...this.collections.values()];
	}

	notePathFor(key: string): string | undefined {
		return this.noteRegistry.get(key);
	}

	setNotePath(key: string, path: string): void {
		if (this.noteRegistry.get(key) === path) return;
		this.noteRegistry.set(key, path);
		void this.writeNotesRegistry();
	}

	removeNotePath(key: string): void {
		if (!this.noteRegistry.delete(key)) return;
		void this.writeNotesRegistry();
	}

	/** Full API record for an item key. */
	async fullRecord(key: string): Promise<ZoteroItem | null> {
		const p = this.itemPath(key);
		if (!(await this.adapter.exists(p))) return null;
		try {
			return JSON.parse(await this.adapter.read(p)) as ZoteroItem;
		} catch {
			return null;
		}
	}

	async childRecords(parentKey: string): Promise<{ item: ZoteroItem; summary: ItemSummary }[]> {
		const keys = this.childrenOf(parentKey);
		const out: { item: ZoteroItem; summary: ItemSummary }[] = [];
		for (const k of keys) {
			const summary = this.items.get(k);
			if (!summary) continue;
			const item = await this.fullRecord(k);
			if (item) out.push({ item, summary });
		}
		return out;
	}

	/** Top-level "citable" items (bibliographic records + standalone notes), for note generation. */
	topLevelCitable(): ItemSummary[] {
		const out: ItemSummary[] = [];
		for (const s of this.items.values()) {
			if (s.parentItem) continue;
			if (s.itemType === 'attachment') continue;
			out.push(s);
		}
		return out;
	}

	relativeLinkFromNoteFolder(targetPath: string): string {
		// Note folder and mirror are both inside the vault: give an Obsidian
		// path-style link the resolver can find even when mirror is hidden.
		return normalizePath(targetPath);
	}

	// ---------- item mutations ----------

	/** Persist one changed/added item record + update the in-memory model. */
	async upsertItem(item: ZoteroItem): Promise<void> {
		await this.writeText(this.itemPath(item.key), JSON.stringify(item, null, 2) + '\n');
		const oldSummary = this.items.get(item.key);
		if (oldSummary?.parentItem && oldSummary.parentItem !== item.data.parentItem) {
			this.detachChild(item.key, oldSummary.parentItem);
		}
		if (oldSummary?.itemType === 'attachment' || item.data.itemType === 'attachment') {
			this.dirtyAttachments.add(item.key);
		}
		const summary = summarizeItem(item);
		this.upsertSummary(summary);
		this.markIndexDirty();

		const type = item.data.itemType;
		if (type === 'annotation') {
			const parent = item.data.parentItem;
			if (parent) this.dirtyAttachments.add(parent);
		} else if (type === 'attachment') {
			// its own annotation file header may embed filename/title
			this.dirtyAttachments.add(item.key);
		}
		// annotations that moved away from an attachment we don't track here; reconcile handles removals
	}

	/** Delete one item file + model entry. Returns true when something existed. */
	async removeItem(key: string): Promise<boolean> {
		const summary = this.items.get(key);
		const existed = !!(summary || (await this.adapter.exists(this.itemPath(key))));
		if (summary) {
			if (summary.itemType === 'attachment') {
				this.dirtyAttachments.delete(key);
				await this.removeIfExists(this.annotationPath(key));
			}
			if (summary.parentItem) this.detachChild(key, summary.parentItem);
			if (summary.itemType === 'annotation' && summary.parentItem) {
				this.dirtyAttachments.add(summary.parentItem);
			}
			this.items.delete(key);
			this.markIndexDirty();
		}
		await this.removeIfExists(this.itemPath(key));
		return existed;
	}

	private detachChild(childKey: string, parentKey: string): void {
		const set = this.children.get(parentKey);
		if (set) {
			set.delete(childKey);
			if (set.size === 0) this.children.delete(parentKey);
		}
	}

	// ---------- collections ----------

	/** Returns the number of collections whose content actually changed. */
	async upsertCollections(list: ZoteroCollection[]): Promise<number> {
		let changed = 0;
		for (const c of list) {
			const s: CollectionSummary = {
				key: c.key,
				version: c.version,
				name: c.data?.name ?? c.key,
				parentCollection: c.data?.parentCollection ?? false,
			};
			const old = this.collections.get(c.key);
			if (!old || old.name !== s.name || old.parentCollection !== s.parentCollection || old.version !== s.version) {
				changed++;
			}
			this.collections.set(c.key, s);
		}
		if (changed > 0) this.collectionsDirty = true;
		return changed;
	}

	removeCollections(keys: string[]): void {
		for (const k of keys) if (this.collections.delete(k)) this.collectionsDirty = true;
	}

	// ---------- derived writes ----------

	markIndexDirty(): void {
		this.indexDirty = true;
	}

	/** Render dirty annotation aggregation files, index, collections, state. */
	async commitDerived(libraryVersion: number, force: boolean): Promise<void> {
		const changed = this.indexDirty || this.collectionsDirty || this.stateDirty || this.dirtyAttachments.size > 0;
		if (!changed && !force) return;
		await this.ensureDirectories();

		if (this.dirtyAttachments.size > 0 || force) {
			const dirty = force ? new Set(this.attachmentKeysWithChildren()) : new Set(this.dirtyAttachments);
			for (const key of dirty) {
				await this.writeAnnotationFile(key, libraryVersion);
			}
			this.dirtyAttachments.clear();
		}

		if (this.collectionsDirty) {
			const cols = [...this.collections.values()].sort((a, b) => (a.name || '').localeCompare(b.name || ''));
			await this.writeText(this.collectionsPath(), JSON.stringify(cols, null, 2) + '\n');
			this.collectionsDirty = false;
		}

		if (this.indexDirty) {
			await this.writeIndex(libraryVersion);
			this.indexDirty = false;
		}

		if (this.stateDirty) {
			await this.saveState();
			this.stateDirty = false;
		}
	}

	/** Persist the search index (regenerable summary of every item file). */
	private async writeIndex(libraryVersion: number): Promise<void> {
		const items = [...this.items.values()].sort((a, b) => (a.title ?? '').localeCompare(b.title ?? '') || a.key.localeCompare(b.key));
		const counts = this.computeCounts(items);
		const idx: MirrorIndex = {
			schema: INDEX_SCHEMA,
			source: {
				type: this.state?.sourceType ?? 'local',
				label: this.state?.sourceFingerprint ?? 'unknown',
			},
			generatedAt: isoNow(),
			libraryVersion,
			counts,
			items,
		};
		await this.writeText(this.indexPath(), JSON.stringify(idx, null, 2) + '\n');
	}

	private computeCounts(items: ItemSummary[]) {
		const counts = { items: items.length, attachments: 0, annotations: 0, notes: 0, topLevel: 0 };
		for (const it of items) {
			if (it.itemType === 'attachment') counts.attachments++;
			else if (it.itemType === 'annotation') counts.annotations++;
			else if (it.itemType === 'note') counts.notes++;
			if (!it.parentItem && it.itemType !== 'attachment') counts.topLevel++;
		}
		return counts;
	}

	private attachmentKeysWithChildren(): string[] {
		const keys: string[] = [];
		for (const s of this.items.values()) if (s.itemType === 'attachment') keys.push(s.key);
		for (const s of this.items.values()) if (s.itemType === 'annotation' && s.parentItem) keys.push(s.parentItem);
		return [...new Set(keys)];
	}

	/** Write annotations/<attachmentKey>.json from that attachment's child annotations. */
	private async writeAnnotationFile(attachmentKey: string, libraryVersion: number): Promise<void> {
		const attachItem = await this.fullRecord(attachmentKey);
		const attachData: ZoteroItemData = attachItem?.data ?? ({} as ZoteroItemData);
		const childKeys = this.childrenOf(attachmentKey).filter((k) => this.items.get(k)?.itemType === 'annotation');

		const annotations: AnnotationEntry[] = [];
		for (const ck of childKeys) {
			const rec = await this.fullRecord(ck);
			if (!rec) continue;
			const d = rec.data ?? ({} as ZoteroItemData);
			const pos = this.parseAnnotationPosition(d.annotationPosition);
			annotations.push({
				key: rec.key,
				version: rec.version,
				color: d.annotationColor ?? null,
				colorName: colorName(d.annotationColor),
				pageLabel: d.annotationPageLabel ?? null,
				pageIndex: pos?.pageIndex ?? null,
				text: d.annotationText ?? '',
				comment: d.annotationComment ?? '',
				sortIndex: d.annotationSortIndex ?? null,
				sortPosition: pos?.sortPosition ?? null,
				position: pos?.raw ?? null,
				dateModified: d.dateModified ?? null,
			});
		}
		annotations.sort((a, b) => this.annotationSortRank(a) - this.annotationSortRank(b));

		const file: AnnotationFile = {
			schema: MIRROR_SCHEMA,
			attachmentKey,
			parentItemKey: attachData.parentItem ?? null,
			libraryVersion,
			filename: attachData.filename ?? null,
			title: attachData.title ?? null,
			contentType: attachData.contentType ?? null,
			generatedAt: isoNow(),
			annotations,
		};
		await this.writeText(this.annotationPath(attachmentKey), JSON.stringify(file, null, 2) + '\n');
	}

	private parseAnnotationPosition(raw: string | null | undefined): {
		pageIndex: number | null;
		sortPosition: [number, number] | null;
		raw: unknown;
	} | null {
		if (!raw) return null;
		try {
			const obj: unknown = JSON.parse(raw);
			let pageIndex: number | null = null;
			let sortPosition: [number, number] | null = null;
			if (obj && typeof obj === 'object') {
				const pi = (obj as { pageIndex?: unknown }).pageIndex;
				pageIndex = typeof pi === 'number' ? pi : typeof pi === 'string' ? parseInt(pi, 10) : null;
				const rects = (obj as { rects?: unknown }).rects;
				if (Array.isArray(rects) && rects.length > 0) {
					const first = rects[0] as { x?: unknown; y?: unknown } | undefined;
					if (first && typeof first.x === 'number' && typeof first.y === 'number') {
						sortPosition = [first.x, first.y];
					}
				}
			}
			return { pageIndex, sortPosition, raw: obj };
		} catch {
			return null;
		}
	}

	private annotationSortRank(a: AnnotationEntry): number {
		const si = a.sortIndex;
		if (si) {
			const parts = si.split(',').map((x) => parseFloat(x));
			if (parts.length === 2 && parts.every(Number.isFinite)) {
				return parts[0] * 1e6 + parts[1];
			}
		}
		if (a.sortPosition) return a.sortPosition[0] * 1e6 + a.sortPosition[1] * 1e3;
		return (a.pageIndex ?? 0) * 1e6;
	}

	// ---------- state ----------

	setState(patch: Partial<MirrorState>): void {
		if (!this.state) {
			this.state = {
				schema: MIRROR_SCHEMA,
				sourceType: 'local',
				sourceFingerprint: '',
				serverID: null,
				libraryVersion: 0,
				collectionsVersion: 0,
				hasData: false,
				lastSyncedAt: null,
				lastReconcileAt: null,
				lastError: null,
				counts: { items: 0, annotations: 0 },
			};
			this.stateDirty = true;
		}
		let changed = false;
		const target = this.state as unknown as Record<string, unknown>;
		for (const [k, v] of Object.entries(patch)) {
			if (target[k] !== v) {
				target[k] = v;
				changed = true;
			}
		}
		if (changed) this.stateDirty = true;
	}

	touchState(): void {
		this.stateDirty = true;
	}

	private async saveState(): Promise<void> {
		if (!this.state) return;
		this.state.counts = { items: this.items.size, annotations: this.annotationCount() };
		await this.writeText(this.statePath(), JSON.stringify(this.state, null, 2) + '\n');
	}

	private annotationCount(): number {
		let n = 0;
		for (const s of this.items.values()) if (s.itemType === 'annotation') n++;
		return n;
	}

	private async writeNotesRegistry(): Promise<void> {
		await this.ensureDirectories();
		const obj: Record<string, string> = {};
		for (const [k, v] of this.noteRegistry) obj[k] = v;
		await this.writeText(this.notesPath(), JSON.stringify(obj, null, 2) + '\n');
	}

	// ---------- low-level fs ----------

	private async writeText(path: string, content: string): Promise<void> {
		await this.adapter.write(path, content);
	}

	private async removeIfExists(path: string): Promise<void> {
		if (await this.adapter.exists(path)) {
			try {
				await this.adapter.remove(path);
			} catch {
				/* best effort */
			}
		}
	}
}
